"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultRateLimiterOptions = exports.APIClass = exports.API = void 0;
require("./helpers/composeRoomWithLastMessage");
require("./helpers/getLoggedInUser");
require("./helpers/getPaginationItems");
require("./helpers/getUserFromParams");
require("./helpers/getUserInfo");
require("./helpers/isUserFromParams");
require("./helpers/parseJsonQuery");
require("./default/info");
require("./v1/assets");
require("./v1/calendar");
require("./v1/channels");
require("./v1/chat");
require("./v1/cloud");
require("./v1/commands");
require("./v1/dns");
require("./v1/e2e");
require("./v1/emoji-custom");
require("./v1/groups");
require("./v1/im");
require("./v1/integrations");
require("./v1/invites");
require("./v1/import");
require("./v1/ldap");
require("./v1/misc");
require("./v1/permissions");
require("./v1/presence");
require("./v1/push");
require("./v1/roles");
require("./v1/rooms");
require("./v1/settings");
require("./v1/stats");
require("./v1/subscriptions");
require("./v1/users");
require("./v1/videoConference");
require("./v1/autotranslate");
require("./v1/webdav");
require("./v1/oauthapps");
require("./v1/custom-sounds");
require("./v1/custom-user-status");
require("./v1/instances");
require("./v1/banners");
require("./v1/email-inbox");
require("./v1/mailer");
require("./v1/teams");
require("./v1/voip/extensions");
require("./v1/voip/queues");
require("./v1/voip/omnichannel");
require("./v1/voip");
require("./v1/federation");
require("./v1/moderation");
var api_1 = require("./api");
Object.defineProperty(exports, "API", { enumerable: true, get: function () { return api_1.API; } });
Object.defineProperty(exports, "APIClass", { enumerable: true, get: function () { return api_1.APIClass; } });
Object.defineProperty(exports, "defaultRateLimiterOptions", { enumerable: true, get: function () { return api_1.defaultRateLimiterOptions; } });
