"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnterpriseSettings = exports.User = exports.OmnichannelAnalytics = exports.Import = exports.OmnichannelEEService = exports.Omnichannel = exports.FederationEE = exports.Federation = exports.OmnichannelIntegration = exports.Settings = exports.Translation = exports.Message = exports.OmnichannelTranscript = exports.QueueWorker = exports.Calendar = exports.Upload = exports.VideoConf = exports.DeviceManagement = exports.SAUMonitor = exports.LDAP = exports.Analytics = exports.LivechatVoip = exports.VoipFreeSwitch = exports.VoipAsterisk = exports.Media = exports.Room = exports.MessageReads = exports.Team = exports.NPS = exports.UiKitCoreApp = exports.Banner = exports.MeteorService = exports.License = exports.Account = exports.Presence = exports.Apps = exports.Authorization = exports.dbWatchersDisabled = exports.proxify = exports.ServiceStarter = exports.getTrashCollection = exports.getConnection = exports.ServiceClassInternal = exports.ServiceClass = exports.LocalBroker = exports.api = exports.isMeteorError = exports.MeteorError = exports.traceInstanceMethods = exports.asyncLocalStorage = void 0;
const proxify_1 = require("./lib/proxify");
Object.defineProperty(exports, "proxify", { enumerable: true, get: function () { return proxify_1.proxify; } });
var asyncLocalStorage_1 = require("./lib/asyncLocalStorage");
Object.defineProperty(exports, "asyncLocalStorage", { enumerable: true, get: function () { return asyncLocalStorage_1.asyncLocalStorage; } });
var asyncMethodCallContext_1 = require("./lib/asyncMethodCallContext");
Object.defineProperty(exports, "traceInstanceMethods", { enumerable: true, get: function () { return asyncMethodCallContext_1.traceInstanceMethods; } });
var MeteorError_1 = require("./MeteorError");
Object.defineProperty(exports, "MeteorError", { enumerable: true, get: function () { return MeteorError_1.MeteorError; } });
Object.defineProperty(exports, "isMeteorError", { enumerable: true, get: function () { return MeteorError_1.isMeteorError; } });
var api_1 = require("./api");
Object.defineProperty(exports, "api", { enumerable: true, get: function () { return api_1.api; } });
var LocalBroker_1 = require("./LocalBroker");
Object.defineProperty(exports, "LocalBroker", { enumerable: true, get: function () { return LocalBroker_1.LocalBroker; } });
var ServiceClass_1 = require("./types/ServiceClass");
Object.defineProperty(exports, "ServiceClass", { enumerable: true, get: function () { return ServiceClass_1.ServiceClass; } });
Object.defineProperty(exports, "ServiceClassInternal", { enumerable: true, get: function () { return ServiceClass_1.ServiceClassInternal; } });
var mongo_1 = require("./lib/mongo");
Object.defineProperty(exports, "getConnection", { enumerable: true, get: function () { return mongo_1.getConnection; } });
Object.defineProperty(exports, "getTrashCollection", { enumerable: true, get: function () { return mongo_1.getTrashCollection; } });
var ServiceStarter_1 = require("./lib/ServiceStarter");
Object.defineProperty(exports, "ServiceStarter", { enumerable: true, get: function () { return ServiceStarter_1.ServiceStarter; } });
const disabledEnvVar = String(process.env.DISABLE_DB_WATCHERS).toLowerCase();
exports.dbWatchersDisabled = (process.env.NODE_ENV === 'production' && ['yes', 'true'].includes(disabledEnvVar)) ||
    (process.env.NODE_ENV !== 'production' && !['no', 'false'].includes(disabledEnvVar));
// TODO think in a way to not have to pass the service name to proxify here as well
exports.Authorization = (0, proxify_1.proxify)('authorization');
exports.Apps = (0, proxify_1.proxify)('apps-engine');
exports.Presence = (0, proxify_1.proxify)('presence');
exports.Account = (0, proxify_1.proxify)('accounts');
exports.License = (0, proxify_1.proxify)('license');
exports.MeteorService = (0, proxify_1.proxify)('meteor');
exports.Banner = (0, proxify_1.proxify)('banner');
exports.UiKitCoreApp = (0, proxify_1.proxify)('uikit-core-app');
exports.NPS = (0, proxify_1.proxify)('nps');
exports.Team = (0, proxify_1.proxify)('team');
exports.MessageReads = (0, proxify_1.proxify)('message-reads');
exports.Room = (0, proxify_1.proxify)('room');
exports.Media = (0, proxify_1.proxify)('media');
exports.VoipAsterisk = (0, proxify_1.proxify)('voip-asterisk');
exports.VoipFreeSwitch = (0, proxify_1.proxify)('voip-freeswitch');
exports.LivechatVoip = (0, proxify_1.proxify)('omnichannel-voip');
exports.Analytics = (0, proxify_1.proxify)('analytics');
exports.LDAP = (0, proxify_1.proxify)('ldap');
exports.SAUMonitor = (0, proxify_1.proxify)('sau-monitor');
exports.DeviceManagement = (0, proxify_1.proxify)('device-management');
exports.VideoConf = (0, proxify_1.proxify)('video-conference');
exports.Upload = (0, proxify_1.proxify)('upload');
exports.Calendar = (0, proxify_1.proxify)('calendar');
exports.QueueWorker = (0, proxify_1.proxify)('queue-worker');
exports.OmnichannelTranscript = (0, proxify_1.proxify)('omnichannel-transcript');
exports.Message = (0, proxify_1.proxify)('message');
exports.Translation = (0, proxify_1.proxify)('translation');
exports.Settings = (0, proxify_1.proxify)('settings');
exports.OmnichannelIntegration = (0, proxify_1.proxify)('omnichannel-integration');
exports.Federation = (0, proxify_1.proxify)('federation');
exports.FederationEE = (0, proxify_1.proxify)('federation-enterprise');
exports.Omnichannel = (0, proxify_1.proxify)('omnichannel');
exports.OmnichannelEEService = (0, proxify_1.proxify)('omnichannel-ee');
exports.Import = (0, proxify_1.proxify)('import');
exports.OmnichannelAnalytics = (0, proxify_1.proxify)('omnichannel-analytics');
exports.User = (0, proxify_1.proxify)('user');
// Calls without wait. Means that the service is optional and the result may be an error
// of service/method not available
exports.EnterpriseSettings = (0, proxify_1.proxify)('ee-settings');
