"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const ui_voip_1 = require("@rocket.chat/ui-voip");
const react_1 = __importDefault(require("react"));
const ActionManagerProvider_1 = __importDefault(require("./ActionManagerProvider"));
const AuthenticationProvider_1 = __importDefault(require("./AuthenticationProvider/AuthenticationProvider"));
const AuthorizationProvider_1 = __importDefault(require("./AuthorizationProvider"));
const AvatarUrlProvider_1 = __importDefault(require("./AvatarUrlProvider"));
const CallProvider_1 = require("./CallProvider");
const ConnectionStatusProvider_1 = __importDefault(require("./ConnectionStatusProvider"));
const CustomSoundProvider_1 = __importDefault(require("./CustomSoundProvider"));
const DeviceProvider_1 = require("./DeviceProvider/DeviceProvider");
const EmojiPickerProvider_1 = __importDefault(require("./EmojiPickerProvider"));
const LayoutProvider_1 = __importDefault(require("./LayoutProvider"));
const ModalProvider_1 = __importDefault(require("./ModalProvider/ModalProvider"));
const OmnichannelProvider_1 = __importDefault(require("./OmnichannelProvider"));
const RouterProvider_1 = __importDefault(require("./RouterProvider"));
const ServerProvider_1 = __importDefault(require("./ServerProvider"));
const SessionProvider_1 = __importDefault(require("./SessionProvider"));
const SettingsProvider_1 = __importDefault(require("./SettingsProvider"));
const ToastMessagesProvider_1 = __importDefault(require("./ToastMessagesProvider"));
const TooltipProvider_1 = __importDefault(require("./TooltipProvider"));
const TranslationProvider_1 = __importDefault(require("./TranslationProvider"));
const UserPresenceProvider_1 = __importDefault(require("./UserPresenceProvider"));
const UserProvider_1 = __importDefault(require("./UserProvider"));
const VideoConfProvider_1 = __importDefault(require("./VideoConfProvider"));
const OmnichannelRoomIconProvider_1 = require("../components/RoomIcon/OmnichannelRoomIcon/provider/OmnichannelRoomIconProvider");
const MeteorProvider = ({ children }) => ((0, jsx_runtime_1.jsx)(ConnectionStatusProvider_1.default, { children: (0, jsx_runtime_1.jsx)(ServerProvider_1.default, { children: (0, jsx_runtime_1.jsx)(RouterProvider_1.default, { children: (0, jsx_runtime_1.jsx)(SettingsProvider_1.default, { children: (0, jsx_runtime_1.jsx)(TranslationProvider_1.default, { children: (0, jsx_runtime_1.jsx)(SessionProvider_1.default, { children: (0, jsx_runtime_1.jsx)(TooltipProvider_1.default, { children: (0, jsx_runtime_1.jsx)(ToastMessagesProvider_1.default, { children: (0, jsx_runtime_1.jsx)(LayoutProvider_1.default, { children: (0, jsx_runtime_1.jsx)(AvatarUrlProvider_1.default, { children: (0, jsx_runtime_1.jsx)(UserProvider_1.default, { children: (0, jsx_runtime_1.jsx)(AuthenticationProvider_1.default, { children: (0, jsx_runtime_1.jsx)(CustomSoundProvider_1.default, { children: (0, jsx_runtime_1.jsx)(DeviceProvider_1.DeviceProvider, { children: (0, jsx_runtime_1.jsx)(ModalProvider_1.default, { children: (0, jsx_runtime_1.jsx)(AuthorizationProvider_1.default, { children: (0, jsx_runtime_1.jsx)(EmojiPickerProvider_1.default, { children: (0, jsx_runtime_1.jsx)(OmnichannelRoomIconProvider_1.OmnichannelRoomIconProvider, { children: (0, jsx_runtime_1.jsx)(UserPresenceProvider_1.default, { children: (0, jsx_runtime_1.jsx)(ActionManagerProvider_1.default, { children: (0, jsx_runtime_1.jsx)(VideoConfProvider_1.default, { children: (0, jsx_runtime_1.jsx)(ui_voip_1.VoipProvider, { children: (0, jsx_runtime_1.jsx)(CallProvider_1.CallProvider, { children: (0, jsx_runtime_1.jsx)(OmnichannelProvider_1.default, { children: children }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }));
exports.default = MeteorProvider;
