"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MATRIX_POWER_LEVELS = void 0;
var MATRIX_POWER_LEVELS;
(function (MATRIX_POWER_LEVELS) {
    MATRIX_POWER_LEVELS[MATRIX_POWER_LEVELS["USER"] = 0] = "USER";
    MATRIX_POWER_LEVELS[MATRIX_POWER_LEVELS["MODERATOR"] = 50] = "MODERATOR";
    MATRIX_POWER_LEVELS[MATRIX_POWER_LEVELS["ADMIN"] = 100] = "ADMIN";
})(MATRIX_POWER_LEVELS || (exports.MATRIX_POWER_LEVELS = MATRIX_POWER_LEVELS = {}));
