"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("../imports/server/rest/agent");
require("../imports/server/rest/departments");
require("../imports/server/rest/sms");
require("../imports/server/rest/users");
require("../imports/server/rest/upload");
require("../imports/server/rest/inquiries");
require("../imports/server/rest/rooms");
require("../imports/server/rest/appearance");
require("../imports/server/rest/triggers");
require("../imports/server/rest/integrations");
require("../imports/server/rest/visitors");
require("../imports/server/rest/dashboards");
require("../imports/server/rest/queue");
require("../imports/server/rest/businessHours");
