"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerEEBroker = void 0;
require("./models/startup");
require("../app/license/server");
require("../app/api-enterprise/server/index");
require("../app/authorization/server/index");
require("../app/canned-responses/server/index");
require("../app/livechat-enterprise/server/index");
require("../app/message-read-receipt/server/index");
require("../app/voip-enterprise/server/index");
require("../app/settings/server/index");
require("./api");
require("./requestSeatsRoute");
require("./configuration/index");
require("./local-services/ldap/service");
require("./methods/getReadReceipts");
require("./apps/startup");
require("./patches");
var startup_1 = require("./startup");
Object.defineProperty(exports, "registerEEBroker", { enumerable: true, get: function () { return startup_1.registerEEBroker; } });
