"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PrioritiesSelect = exports.SlaPoliciesSelect = exports.DepartmentForwarding = exports.DepartmentBusinessHours = exports.CurrentChatTags = exports.ContactManagerInput = exports.EeTextInput = exports.BusinessHoursMultiple = exports.EeTextAreaInput = exports.EeNumberInput = exports.MaxChatsPerAgentDisplay = exports.MaxChatsPerAgent = exports.CustomFieldsAdditionalForm = void 0;
const BusinessHoursMultiple_1 = __importDefault(require("../../omnichannel/additionalForms/BusinessHoursMultiple"));
exports.BusinessHoursMultiple = BusinessHoursMultiple_1.default;
const ContactManagerInput_1 = __importDefault(require("../../omnichannel/additionalForms/ContactManagerInput"));
exports.ContactManagerInput = ContactManagerInput_1.default;
const CurrentChatTags_1 = __importDefault(require("../../omnichannel/additionalForms/CurrentChatTags"));
exports.CurrentChatTags = CurrentChatTags_1.default;
const CustomFieldsAdditionalForm_1 = __importDefault(require("../../omnichannel/additionalForms/CustomFieldsAdditionalForm"));
exports.CustomFieldsAdditionalForm = CustomFieldsAdditionalForm_1.default;
const DepartmentBusinessHours_1 = __importDefault(require("../../omnichannel/additionalForms/DepartmentBusinessHours"));
exports.DepartmentBusinessHours = DepartmentBusinessHours_1.default;
const DepartmentForwarding_1 = __importDefault(require("../../omnichannel/additionalForms/DepartmentForwarding"));
exports.DepartmentForwarding = DepartmentForwarding_1.default;
const EeNumberInput_1 = __importDefault(require("../../omnichannel/additionalForms/EeNumberInput"));
exports.EeNumberInput = EeNumberInput_1.default;
const EeTextAreaInput_1 = __importDefault(require("../../omnichannel/additionalForms/EeTextAreaInput"));
exports.EeTextAreaInput = EeTextAreaInput_1.default;
const EeTextInput_1 = __importDefault(require("../../omnichannel/additionalForms/EeTextInput"));
exports.EeTextInput = EeTextInput_1.default;
const MaxChatsPerAgent_1 = __importDefault(require("../../omnichannel/additionalForms/MaxChatsPerAgent"));
exports.MaxChatsPerAgent = MaxChatsPerAgent_1.default;
const MaxChatsPerAgentDisplay_1 = __importDefault(require("../../omnichannel/additionalForms/MaxChatsPerAgentDisplay"));
exports.MaxChatsPerAgentDisplay = MaxChatsPerAgentDisplay_1.default;
const PrioritiesSelect_1 = __importDefault(require("../../omnichannel/additionalForms/PrioritiesSelect"));
exports.PrioritiesSelect = PrioritiesSelect_1.default;
const SlaPoliciesSelect_1 = __importDefault(require("../../omnichannel/additionalForms/SlaPoliciesSelect"));
exports.SlaPoliciesSelect = SlaPoliciesSelect_1.default;
