"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getPath = exports.processDataDownloads = exports.sendFile = exports.sendViaEmail = void 0;
var sendViaEmail_1 = require("./sendViaEmail");
Object.defineProperty(exports, "sendViaEmail", { enumerable: true, get: function () { return sendViaEmail_1.sendViaEmail; } });
var sendFile_1 = require("./sendFile");
Object.defineProperty(exports, "sendFile", { enumerable: true, get: function () { return sendFile_1.sendFile; } });
var processDataDownloads_1 = require("./processDataDownloads");
Object.defineProperty(exports, "processDataDownloads", { enumerable: true, get: function () { return processDataDownloads_1.processDataDownloads; } });
var getPath_1 = require("./getPath");
Object.defineProperty(exports, "getPath", { enumerable: true, get: function () { return getPath_1.getPath; } });
