"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppRolesConverter = exports.AppVisitorsConverter = exports.AppUploadsConverter = exports.AppDepartmentsConverter = exports.AppVideoConferencesConverter = exports.AppUsersConverter = exports.AppSettingsConverter = exports.AppRoomsConverter = exports.AppMessagesConverter = exports.AppContactsConverter = void 0;
const contacts_1 = require("./contacts");
Object.defineProperty(exports, "AppContactsConverter", { enumerable: true, get: function () { return contacts_1.AppContactsConverter; } });
const departments_1 = require("./departments");
Object.defineProperty(exports, "AppDepartmentsConverter", { enumerable: true, get: function () { return departments_1.AppDepartmentsConverter; } });
const messages_1 = require("./messages");
Object.defineProperty(exports, "AppMessagesConverter", { enumerable: true, get: function () { return messages_1.AppMessagesConverter; } });
const roles_1 = require("./roles");
Object.defineProperty(exports, "AppRolesConverter", { enumerable: true, get: function () { return roles_1.AppRolesConverter; } });
const rooms_1 = require("./rooms");
Object.defineProperty(exports, "AppRoomsConverter", { enumerable: true, get: function () { return rooms_1.AppRoomsConverter; } });
const settings_1 = require("./settings");
Object.defineProperty(exports, "AppSettingsConverter", { enumerable: true, get: function () { return settings_1.AppSettingsConverter; } });
const uploads_1 = require("./uploads");
Object.defineProperty(exports, "AppUploadsConverter", { enumerable: true, get: function () { return uploads_1.AppUploadsConverter; } });
const users_1 = require("./users");
Object.defineProperty(exports, "AppUsersConverter", { enumerable: true, get: function () { return users_1.AppUsersConverter; } });
const videoConferences_1 = require("./videoConferences");
Object.defineProperty(exports, "AppVideoConferencesConverter", { enumerable: true, get: function () { return videoConferences_1.AppVideoConferencesConverter; } });
const visitors_1 = require("./visitors");
Object.defineProperty(exports, "AppVisitorsConverter", { enumerable: true, get: function () { return visitors_1.AppVisitorsConverter; } });
