"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("codemirror/addon/fold/brace-fold.js");
require("codemirror/addon/fold/comment-fold.js");
require("codemirror/addon/fold/foldcode.js");
require("codemirror/addon/fold/foldgutter.css");
require("codemirror/addon/fold/foldgutter.js");
require("codemirror/addon/fold/indent-fold.js");
require("codemirror/addon/fold/markdown-fold.js");
require("codemirror/addon/fold/xml-fold.js");
// lints
// import 'codemirror/addon/lint/jsonlint.js';
// import 'codemirror/addon/lint/jshint.js';
// import 'codemirror/addon/lint/csslint.js';
// import 'codemirror/addon/lint/css-lint.js';
// import 'codemirror/addon/lint/html-lint.js';
// import 'codemirror/addon/lint/javascript-lint.js';
// import 'codemirror/addon/lint/json-lint.js';
// import 'codemirror/addon/lint/yaml-lint.js';
// import 'codemirror/addon/lint/lint.css';
// import 'codemirror/addon/lint/lint.js';
// active line mode
require("codemirror/addon/selection/active-line.js");
// search/replace
require("codemirror/addon/search/search.js");
require("codemirror/addon/search/searchcursor.js");
require("codemirror/addon/dialog/dialog.js");
require("codemirror/addon/dialog/dialog.css");
// overlay: required by `gfm.js`
require("codemirror/addon/mode/overlay.js");
// markdown list continuation; nice complement for gfm
require("codemirror/addon/edit/continuelist.js");
// modes
require("codemirror/mode/apl/apl.js");
require("codemirror/mode/asterisk/asterisk.js");
require("codemirror/mode/clike/clike.js");
require("codemirror/mode/clojure/clojure.js");
require("codemirror/mode/cobol/cobol.js");
require("codemirror/mode/commonlisp/commonlisp.js");
require("codemirror/mode/coffeescript/coffeescript.js");
require("codemirror/mode/css/css.js");
require("codemirror/mode/cypher/cypher.js");
require("codemirror/mode/d/d.js");
require("codemirror/mode/diff/diff.js");
require("codemirror/mode/django/django.js");
require("codemirror/mode/dockerfile/dockerfile.js");
require("codemirror/mode/dtd/dtd.js");
require("codemirror/mode/dylan/dylan.js");
require("codemirror/mode/ecl/ecl.js");
require("codemirror/mode/eiffel/eiffel.js");
require("codemirror/mode/erlang/erlang.js");
require("codemirror/mode/fortran/fortran.js");
require("codemirror/mode/gas/gas.js");
require("codemirror/mode/gfm/gfm.js");
require("codemirror/mode/gherkin/gherkin.js");
require("codemirror/mode/go/go.js");
require("codemirror/mode/groovy/groovy.js");
require("codemirror/mode/haml/haml.js");
require("codemirror/mode/haskell/haskell.js");
require("codemirror/mode/haxe/haxe.js");
require("codemirror/mode/htmlembedded/htmlembedded.js");
require("codemirror/mode/htmlmixed/htmlmixed.js");
require("codemirror/mode/http/http.js");
require("codemirror/mode/idl/idl.js");
require("codemirror/mode/javascript/javascript.js");
require("codemirror/mode/jinja2/jinja2.js");
require("codemirror/mode/julia/julia.js");
require("codemirror/mode/livescript/livescript.js");
require("codemirror/mode/lua/lua.js");
require("codemirror/mode/markdown/markdown.js");
require("codemirror/mode/mirc/mirc.js");
require("codemirror/mode/mllike/mllike.js");
require("codemirror/mode/modelica/modelica.js");
require("codemirror/mode/nginx/nginx.js");
require("codemirror/mode/ntriples/ntriples.js");
require("codemirror/mode/octave/octave.js");
require("codemirror/mode/pascal/pascal.js");
require("codemirror/mode/pegjs/pegjs.js");
require("codemirror/mode/perl/perl.js");
require("codemirror/mode/php/php.js");
require("codemirror/mode/pig/pig.js");
require("codemirror/mode/properties/properties.js");
require("codemirror/mode/puppet/puppet.js");
require("codemirror/mode/python/python.js");
require("codemirror/mode/q/q.js");
require("codemirror/mode/r/r.js");
require("codemirror/mode/rpm/rpm.js");
require("codemirror/mode/rst/rst.js");
require("codemirror/mode/ruby/ruby.js");
require("codemirror/mode/rust/rust.js");
require("codemirror/mode/sass/sass.js");
require("codemirror/mode/scheme/scheme.js");
require("codemirror/mode/shell/shell.js");
require("codemirror/mode/sieve/sieve.js");
require("codemirror/mode/slim/slim.js");
require("codemirror/mode/smalltalk/smalltalk.js");
require("codemirror/mode/smarty/smarty.js");
require("codemirror/mode/solr/solr.js");
require("codemirror/mode/sparql/sparql.js");
require("codemirror/mode/sql/sql.js");
require("codemirror/mode/stex/stex.js");
require("codemirror/mode/tcl/tcl.js");
require("codemirror/mode/textile/textile.js");
require("codemirror/mode/tiddlywiki/tiddlywiki.js");
require("codemirror/mode/tiki/tiki.js");
require("codemirror/mode/toml/toml.js");
require("codemirror/mode/tornado/tornado.js");
require("codemirror/mode/turtle/turtle.js");
require("codemirror/mode/vb/vb.js");
require("codemirror/mode/vbscript/vbscript.js");
require("codemirror/mode/velocity/velocity.js");
require("codemirror/mode/verilog/verilog.js");
require("codemirror/mode/xml/xml.js");
require("codemirror/mode/xquery/xquery.js");
require("codemirror/mode/yaml/yaml.js");
require("codemirror/mode/z80/z80.js");
// themes
// import 'codemirror/theme/3024-day.css';
// import 'codemirror/theme/3024-night.css';
// import 'codemirror/theme/ambiance-mobile.css';
// import 'codemirror/theme/ambiance.css';
// import 'codemirror/theme/base16-dark.css';
// import 'codemirror/theme/base16-light.css';
// import 'codemirror/theme/blackboard.css';
// import 'codemirror/theme/cobalt.css';
// import 'codemirror/theme/eclipse.css';
// import 'codemirror/theme/elegant.css';
// import 'codemirror/theme/erlang-dark.css';
// import 'codemirror/theme/lesser-dark.css';
// import 'codemirror/theme/mbo.css';
// import 'codemirror/theme/mdn-like.css';
// import 'codemirror/theme/midnight.css';
// import 'codemirror/theme/monokai.css';
// import 'codemirror/theme/neat.css';
// import 'codemirror/theme/neo.css';
// import 'codemirror/theme/night.css';
// import 'codemirror/theme/paraiso-dark.css';
// import 'codemirror/theme/paraiso-light.css';
// import 'codemirror/theme/pastel-on-dark.css';
// import 'codemirror/theme/rubyblue.css';
// import 'codemirror/theme/solarized.css';
// import 'codemirror/theme/the-matrix.css';
// import 'codemirror/theme/tomorrow-night-eighties.css';
// import 'codemirror/theme/twilight.css';
// import 'codemirror/theme/vibrant-ink.css';
// import 'codemirror/theme/xq-dark.css';
// import 'codemirror/theme/xq-light.css';
// key bindings
// import 'codemirror/keymap/emacs.js';
require("codemirror/keymap/sublime.js");
// import 'codemirror/keymap/vim.js';
