"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.VoipSettingsButton = exports.VoipActions = exports.VoipActionButton = exports.VoipContactId = exports.VoipStatus = exports.VoipTimer = exports.VoipDialPad = void 0;
var VoipDialPad_1 = require("./VoipDialPad");
Object.defineProperty(exports, "VoipDialPad", { enumerable: true, get: function () { return __importDefault(VoipDialPad_1).default; } });
var VoipTimer_1 = require("./VoipTimer");
Object.defineProperty(exports, "VoipTimer", { enumerable: true, get: function () { return __importDefault(VoipTimer_1).default; } });
var VoipStatus_1 = require("./VoipStatus");
Object.defineProperty(exports, "VoipStatus", { enumerable: true, get: function () { return __importDefault(VoipStatus_1).default; } });
var VoipContactId_1 = require("./VoipContactId");
Object.defineProperty(exports, "VoipContactId", { enumerable: true, get: function () { return __importDefault(VoipContactId_1).default; } });
var VoipActionButton_1 = require("./VoipActionButton");
Object.defineProperty(exports, "VoipActionButton", { enumerable: true, get: function () { return __importDefault(VoipActionButton_1).default; } });
var VoipActions_1 = require("./VoipActions");
Object.defineProperty(exports, "VoipActions", { enumerable: true, get: function () { return __importDefault(VoipActions_1).default; } });
var VoipSettingsButton_1 = require("./VoipSettingsButton");
Object.defineProperty(exports, "VoipSettingsButton", { enumerable: true, get: function () { return __importDefault(VoipSettingsButton_1).default; } });
